### ISSUE TITLE
Need to minimise number of read accesses to the database

### ISSUE THREAD

**Issue by tvercaut** [MIDL-Conference/shared-timer#1]
With the current implementation, we exhaust the free firebase quotas very rapidly. It might be that relying on the `onSnapshot` method or similar to "listen to changes" rather than proactively query could fix this:
https://firebase.google.com/docs/firestore/query-data/listen

**Comment by fepegar** [comment]
I think the maximum number of document reads per day for the [Free plan is 50 000](https://firebase.google.com/docs/firestore/quotas#free-quota). If two computers are running the timer, that makes it 25 000 seconds or 7 hours. As we don't currently know if there are any other instances running and new experimentation with code might take long, shall we just delete the current project and create a new one with the same code?

**Comment by tvercaut** [comment]
I got a paid plan with free credits for the duration of the conference. Let's hope the free credits will be sufficient for 3 days!

**Comment by tvercaut** [comment]
Actually, let me disable billing for now. I checked it works and will reactivate it when the conference starts.
